---
id: grafana
name: Grafana
summary: Display Grafana Metrics
desc: Show value or graph of Grafana metrics.
author: tavdog
fileName: grafana.star
packageName: grafana
category: utilities
tags:
  - tech
  - data-visual
  - utility
